version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /linux-host-agent
    schedule:
      interval: weekly
